// src/store/tools.ts — 工具 Schema 定义(纯数据)
// 从 chat.ts 拆分, 降低单文件复杂度
// v0.3.0 M1: TOOLS 类型化为 ToolSpec[](结构本身已符合, 仅补类型标注)
// v0.4.4 精简: 与 electron/engine/tool-specs.ts 保持一致 —— 仅保留 工具调用/插件/MCP 相关工具
import type { ToolSpec } from '../types'
import { useAgents } from './agents'
import { filterToolsCore } from '../../electron/shared/tool-filter'

export function filterToolsByAgent(tools: ToolSpec[], agentName: string): ToolSpec[] {
  return filterToolsCore(tools, agentName, useAgents(), { includeMcp: false })
}

export const TOOLS: ToolSpec[] = [
  { type: 'function', function: { name: 'read', description: 'read(path, offset?, limit?) 读取文件(UTF-8); 大文件用 offset/limit 分段续读', parameters: { type: 'object', properties: { path: { type: 'string' }, offset: { type: 'number' }, limit: { type: 'number' } }, required: ['path'] } } },
  { type: 'function', function: { name: 'update_plan', description: 'update_plan(steps, explanation?) 声明或更新任务执行计划: steps=[{label, status?, expected?, tool?, id?}], status 取值 pending/running/done/failed, tool 填将执行的工具名(如 read/write/apply_patch/exec_command/terminal_open); 复杂任务先用它列出完整步骤, 执行中持续更新状态并保持准确', parameters: { type: 'object', properties: { steps: { type: 'array', items: { type: 'object', properties: { id: { type: 'string' }, label: { type: 'string' }, status: { type: 'string', enum: ['pending', 'running', 'done', 'failed'] }, expected: { type: 'string' }, tool: { type: 'string' } } } }, explanation: { type: 'string' } }, required: ['steps'] } } },
  { type: 'function', function: { name: 'write', description: 'write(path, content) 创建或覆盖写入文件', parameters: { type: 'object', properties: { path: { type: 'string' }, content: { type: 'string' } }, required: ['path', 'content'] } } },
  { type: 'function', function: { name: 'edit', description: 'edit(path, oldText, newText) 精确文本替换(全文替换首个匹配)', parameters: { type: 'object', properties: { path: { type: 'string' }, oldText: { type: 'string' }, newText: { type: 'string' } }, required: ['path', 'oldText', 'newText'] } } },
  { type: 'function', function: { name: 'apply_patch', description: 'apply_patch(path, hunks) 多 hunk 结构化编辑: hunks=[{oldText, newText}], 按顺序精确替换, 每个 oldText 必须唯一匹配(推荐带足够上下文); 一次调用可完成多处修改', parameters: { type: 'object', properties: { path: { type: 'string' }, hunks: { type: 'array', items: { type: 'object', properties: { oldText: { type: 'string' }, newText: { type: 'string' } }, required: ['oldText', 'newText'] } } }, required: ['path', 'hunks'] } } },
  { type: 'function', function: { name: 'exec_command', description: 'exec_command(cmd) 在 Windows 执行一次性命令(工作目录内)。请使用 PowerShell 语法；含中文路径/输出的命令会自动以 UTF-8 执行，纯 ASCII 简单命令走 cmd', parameters: { type: 'object', properties: { cmd: { type: 'string' } }, required: ['cmd'] } } },
  { type: 'function', function: { name: 'git', description: 'git(action, args?) 在工作目录执行 Git 操作: action 取 status/diff/log/commit/stash/push/pull/checkout, args 为附加参数(如 commit 的 -am "msg")。改代码前先 status/diff, 改完用 diff 验证, 确认后 commit', parameters: { type: 'object', properties: { action: { type: 'string', enum: ['status', 'diff', 'log', 'commit', 'stash', 'push', 'pull', 'checkout'] }, args: { type: 'string' } }, required: ['action'] } } },
  { type: 'function', function: { name: 'init_project_docs', description: 'init_project_docs() 扫描工作目录生成 AGENTS.md 项目指令草稿(项目概览/常用命令/目录结构/默认约定); 已存在时不覆盖。首次进入新项目且没有项目指令时使用', parameters: { type: 'object', properties: {}, required: [] } } },
  { type: 'function', function: { name: 'terminal_open', description: 'terminal_open(id, shell?, cwd?) 打开长驻交互终端会话(id 自定义如 term1; shell: powershell/cmd/node/python), 保持工作目录与状态, 之后用 terminal_run 输入命令', parameters: { type: 'object', properties: { id: { type: 'string' }, shell: { type: 'string', enum: ['powershell', 'cmd', 'node', 'python'] }, cwd: { type: 'string' } }, required: ['id'] } } },
  { type: 'function', function: { name: 'terminal_run', description: 'terminal_run(id, input, wait_ms?) 向终端会话输入命令/表达式并等待输出(默认等 1500ms, 最长 15000ms); 适合 REPL、git、npm 等需要保持状态的交互命令。输入请使用 ASCII 命令；含中文路径/文本的命令请改用 exec_command', parameters: { type: 'object', properties: { id: { type: 'string' }, input: { type: 'string' }, wait_ms: { type: 'number' } }, required: ['id', 'input'] } } },
  { type: 'function', function: { name: 'terminal_close', description: 'terminal_close(id) 关闭终端会话', parameters: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'] } } },
  { type: 'function', function: { name: 'mkdir', description: 'mkdir(path) 创建目录(可递归)', parameters: { type: 'object', properties: { path: { type: 'string' } }, required: ['path'] } } },
  { type: 'function', function: { name: 'grep', description: 'grep(dirPath, pattern) 在目录文件中搜索文本(正则)', parameters: { type: 'object', properties: { dirPath: { type: 'string' }, pattern: { type: 'string' } }, required: ['dirPath', 'pattern'] } } },
  { type: 'function', function: { name: 'find', description: 'find(dirPath, glob) 按 glob 模式查找文件', parameters: { type: 'object', properties: { dirPath: { type: 'string' }, glob: { type: 'string' } }, required: ['dirPath', 'glob'] } } },
  { type: 'function', function: { name: 'ls', description: 'ls(dirPath?) 列出目录内容(默认工作目录)', parameters: { type: 'object', properties: { dirPath: { type: 'string' } } } } },
  { type: 'function', function: { name: 'system_info', description: 'system_info() 获取 CPU/内存/GPU 系统信息', parameters: { type: 'object', properties: {} } } },
  { type: 'function', function: { name: 'web_search', description: 'web_search(query) 网络搜索', parameters: { type: 'object', properties: { query: { type: 'string' } }, required: ['query'] } } },
  { type: 'function', function: { name: 'web_fetch', description: 'web_fetch(url) 抓取网页内容', parameters: { type: 'object', properties: { url: { type: 'string' } }, required: ['url'] } } },
  { type: 'function', function: { name: 'web_read', description: 'web_read(url, mode?) 无头浏览器解析网页正文(text|screenshot|pdf); 仅单页解析, 禁止批量抓取', parameters: { type: 'object', properties: { url: { type: 'string' }, mode: { type: 'string', enum: ['text', 'screenshot', 'pdf'] } }, required: ['url'] } } },
  { type: 'function', function: { name: 'browse', description: 'browse(url?) 无头浏览器打开网页并返回可访问性快照: 标题/正文 + 可交互元素列表(带 @编号, 如 @1 [link] 文档)。后续可用 browser_click/browser_type 操作页面', parameters: { type: 'object', properties: { url: { type: 'string', description: '要打开的网址; 省略则快照当前页面' } } } } },
  { type: 'function', function: { name: 'browse_screenshot', description: 'browse_screenshot(url) 对网页截图', parameters: { type: 'object', properties: { url: { type: 'string' } }, required: ['url'] } } },
  { type: 'function', function: { name: 'browser_click', description: 'browser_click(ref) 点击页面中 @编号 的元素(ref 来自 browse 快照)', parameters: { type: 'object', properties: { ref: { type: 'string', description: '形如 @1' } }, required: ['ref'] } } },
  { type: 'function', function: { name: 'browser_type', description: 'browser_type(ref, text) 向 @编号 输入框输入文字(输入前建议先 browser_click 聚焦)', parameters: { type: 'object', properties: { ref: { type: 'string' }, text: { type: 'string' } }, required: ['ref', 'text'] } } },
  { type: 'function', function: { name: 'browser_press', description: 'browser_press(key) 按下按键: Enter/Escape/Tab/ArrowDown/ArrowUp/ArrowLeft/ArrowRight/Backspace/空格 等', parameters: { type: 'object', properties: { key: { type: 'string' } }, required: ['key'] } } },
  { type: 'function', function: { name: 'browser_scroll', description: 'browser_scroll(direction) 页面滚动: down(向下)/up(向上)', parameters: { type: 'object', properties: { direction: { type: 'string', enum: ['down', 'up'] } }, required: ['direction'] } } },
  { type: 'function', function: { name: 'browser_console', description: 'browser_console(expression) 在当前浏览器页面执行 JavaScript 并返回结果(用于读取页面状态/触发页面逻辑)', parameters: { type: 'object', properties: { expression: { type: 'string' } }, required: ['expression'] } } },
  { type: 'function', function: { name: 'browser_vision', description: 'browser_vision(question) 对当前浏览器页面截图并用视觉模型回答(适合需要看图才能完成的网页操作/验证)', parameters: { type: 'object', properties: { question: { type: 'string' } }, required: ['question'] } } },
  { type: 'function', function: { name: 'screenshot', description: 'screenshot() 截取屏幕', parameters: { type: 'object', properties: {} } } },
  { type: 'function', function: { name: 'clipboard_read', description: 'clipboard_read() 读取剪贴板文本', parameters: { type: 'object', properties: {} } } },
  { type: 'function', function: { name: 'clipboard_write', description: 'clipboard_write(text) 写入剪贴板', parameters: { type: 'object', properties: { text: { type: 'string' } }, required: ['text'] } } },
  { type: 'function', function: { name: 'process_list', description: 'process_list() 列出运行中进程', parameters: { type: 'object', properties: {} } } },
  { type: 'function', function: { name: 'kill_process', description: 'kill_process(pid) 按 PID 结束进程', parameters: { type: 'object', properties: { pid: { type: 'string' } }, required: ['pid'] } } },
  { type: 'function', function: { name: 'codebox', description: 'codebox(lang, code) 沙箱运行 Python/Node 代码(lang: python|node)', parameters: { type: 'object', properties: { lang: { type: 'string' }, code: { type: 'string' } }, required: ['lang', 'code'] } } },
  { type: 'function', function: { name: 'desktop_screenshot', description: 'desktop_screenshot() 截取当前全屏画面并返回图片路径(配合 read_image 让视觉模型分析), 之后可用 desktop_click/type/key 操作任意应用', parameters: { type: 'object', properties: {} } } },
  { type: 'function', function: { name: 'desktop_click', description: 'desktop_click(x, y, button?) 在屏幕坐标(x,y)点击(button=2 右键, 默认左键), 坐标来自屏幕截图视觉定位', parameters: { type: 'object', properties: { x: { type: 'number' }, y: { type: 'number' }, button: { type: 'number' } }, required: ['x', 'y'] } } },
  { type: 'function', function: { name: 'desktop_move', description: 'desktop_move(x, y) 把鼠标移动到屏幕坐标(x,y)', parameters: { type: 'object', properties: { x: { type: 'number' }, y: { type: 'number' } }, required: ['x', 'y'] } } },
  { type: 'function', function: { name: 'desktop_scroll', description: 'desktop_scroll(x, y, delta) 在屏幕坐标(x,y)滚动滚轮(delta 正=向上滚/负=向下, 约 120=一格)', parameters: { type: 'object', properties: { x: { type: 'number' }, y: { type: 'number' }, delta: { type: 'number' } }, required: ['x', 'y', 'delta'] } } },
  { type: 'function', function: { name: 'desktop_type', description: 'desktop_type(text) 向当前聚焦窗口输入文本(自动粘贴, 支持中文/换行)', parameters: { type: 'object', properties: { text: { type: 'string' } }, required: ['text'] } } },
  { type: 'function', function: { name: 'desktop_key', description: 'desktop_key(key) 发送按键组合(SendKeys 语法: ^c=Ctrl+C, %{F4}=Alt+F4, {ENTER}, {TAB}, {ESC})', parameters: { type: 'object', properties: { key: { type: 'string' } }, required: ['key'] } } },
  { type: 'function', function: { name: 'read_image', description: 'read_image(path) 读取图片为 dataURL(脚本内部用; 用户提供图片路径时系统自动处理)', parameters: { type: 'object', properties: { path: { type: 'string' } }, required: ['path'] } } },
  { type: 'function', function: { name: 'mcp_connect', description: 'mcp_connect(name, command, args) 连接 MCP 服务器(args 为字符串数组)', parameters: { type: 'object', properties: { name: { type: 'string' }, command: { type: 'string' }, args: { type: 'array', items: { type: 'string' } } }, required: ['name', 'command'] } } },
  { type: 'function', function: { name: 'mcp_call', description: 'mcp_call(server, tool, args) 调用 MCP 工具', parameters: { type: 'object', properties: { server: { type: 'string' }, tool: { type: 'string' }, args: { type: 'object' } }, required: ['server', 'tool'] } } },
  { type: 'function', function: { name: 'set_workdir', description: 'set_workdir(path) 切换工作目录(本次会话)', parameters: { type: 'object', properties: { path: { type: 'string' } }, required: ['path'] } } },
  { type: 'function', function: { name: 'set_theme', description: 'set_theme(theme) 切换主题', parameters: { type: 'object', properties: { theme: { type: 'string' } }, required: ['theme'] } } },
  { type: 'function', function: { name: 'clarify', description: 'clarify(question, choices?) 当用户意图不明确、缺少关键信息或需要在多个方案中选择时，暂停并向用户提出带选项的问题。返回用户选择的回答。choices 可提供 2-6 个选项（可选），multi_select=true 时用户可多选（返回 JSON 数组字符串）', parameters: { type: 'object', properties: { question: { type: 'string', description: '要问用户的问题（简洁明确）' }, choices: { type: 'array', items: { type: 'string' }, description: '可选的可选项列表，2-6 个' }, multi_select: { type: 'boolean', description: '是否允许用户多选' } }, required: ['question'] } } },
  { type: 'function', function: { name: 'show_card', description: 'show_card(html, title?) 渲染交互卡片(SVG/图表/示意图)', parameters: { type: 'object', properties: { html: { type: 'string' }, title: { type: 'string' } }, required: ['html'] } } },
  { type: 'function', function: { name: 'set_ui_display', description: 'set_ui_display(patches) 按用户自然语言要求调节界面显示。patches 为 JSON 对象, 可选字段: hiddenNav(["agents","browser","files"] 的数组, chat/settings 不可隐藏); hideSessionSearch/hideSessionList/hidePlanCards/hideChatToolbar/hideAttachmentBar/hideModelPicker/hideThinkSelector/hideTokenUsage/hideTimestamps/hideToolCalls/hideTokenMeta/hideCopyButtons/hideRegenerate(布尔); statusLine(模板字符串, 插值 ${workDir}/${model}/${context}/${tokens}/${agents}, 传空串恢复默认); density("compact"|"comfortable"|"spacious"); customCss(字符串, 传空串清除)。未传字段保持不变, 只传要改的字段', parameters: { type: 'object', properties: { patches: { type: 'object', description: '要修改的界面字段(键值对)' } }, required: ['patches'] } } },
  { type: 'function', function: { name: 'get_ui_display', description: 'get_ui_display() 查看当前界面显示配置(用于向用户确认或回答当前显示状态)', parameters: { type: 'object', properties: {} } } },
  { type: 'function', function: { name: 'get_settings', description: 'get_settings(section?) 读取当前设置。section 取 general(默认)/providers/mediaProviders/all; 密钥与凭证已脱敏显示为 ***, 不进入上下文', parameters: { type: 'object', properties: { section: { type: 'string', enum: ['general', 'providers', 'mediaProviders', 'all'] } } } } },
  { type: 'function', function: { name: 'set_settings', description: 'set_settings(patch, section?) 按用户自然语言要求修改设置(立即生效并保存)。section 默认 general; patch 为对象, 支持: theme/mode/agentName/language/region/workDir/uiFontSize/codeFontSize/chatMaxWidth/opacity/animation/showTimestamps/autoCopy/useTables/useLists/useEmoji/expressUncertainty/askWhenMissing/showConfidence/explainRefusal/neutralOnControversial/noClosingPhrase/briefClosing/customSystemPrompt/promptInjectPos/thinkLevel/thinkOverrides/sp/ishiki/mainModel/fastModel/longTextModel/codeModel/autoFastModel/toolPerms/perf/customColors/customTheme/skinColors/skinSecondary/uiDisplay/mcpTimeout/mcpAutoConnectOnStart/mcpAutoReconnect/browserHomeUrl/compactStrategy/compactMsgCount/compactTokenLimit/compactStrength/taskArchive。providers 传数组[{id,...}] 只改非密钥字段。密钥/风险放行/命令黑名单等安全项拒绝经对话修改', parameters: { type: 'object', properties: { patch: { type: 'object', description: '要修改的字段(键值对)' }, section: { type: 'string', enum: ['general', 'providers'] } }, required: ['patch'] } } },
  { type: 'function', function: { name: 'install_plugin', description: 'install_plugin(name, description, code, overwrite?, settings?) 给自己写插件并安装: 校验通过自动生成 manifest 并热加载, 无需重启, 下一轮即可按 plugin_<name>__<tool> 调用。code 为 CommonJS 源码, 协议 module.exports={tools:[{name,description,params:{参数:类型},run(args,ctx){return "结果"}}]}; run 内可用 ctx.tools.run("read"/"write"/"exec_command",args)、ctx.log(text) 与 ctx.settings(用户可配置项)。settings 可选数组 [{key,label,type:"string"|"number"|"boolean"|"select",default?,options?,hint?}], 会在插件页自动生成设置卡片', parameters: { type: 'object', properties: { name: { type: 'string', description: '插件目录名, 小写字母数字开头, 1-80 位 [a-z0-9_-]' }, description: { type: 'string', description: '插件一句话说明(≤500 字)' }, code: { type: 'string', description: 'index.js 完整源码' }, overwrite: { type: 'boolean', description: '已存在时是否覆盖更新(版本号自动 +1)' }, settings: { type: 'array', description: '插件设置 schema(可选)', items: { type: 'object', properties: { key: { type: 'string' }, label: { type: 'string' }, type: { type: 'string', enum: ['string', 'number', 'boolean', 'select'] }, default: { type: 'string' }, options: { type: 'array', items: { type: 'string' } }, hint: { type: 'string' } }, required: ['key', 'label'] } } }, required: ['name', 'description', 'code'] } } },
  { type: 'function', function: { name: 'list_plugins', description: 'list_plugins() 列出已安装插件、来源(自写/外部)与可用工具', parameters: { type: 'object', properties: {} } } },
  { type: 'function', function: { name: 'read_plugin', description: 'read_plugin(name) 读取插件 manifest.json 与 index.js 源码(用于修订后再 install_plugin 覆盖)', parameters: { type: 'object', properties: { name: { type: 'string' } }, required: ['name'] } } },
  { type: 'function', function: { name: 'remove_plugin', description: 'remove_plugin(name) 删除插件(需用户确认, 删除后立即失效)', parameters: { type: 'object', properties: { name: { type: 'string' } }, required: ['name'] } } },
  { type: 'function', function: { name: 'reload_plugins', description: 'reload_plugins() 重新扫描插件目录并刷新工具列表(手动修改插件文件后调用)', parameters: { type: 'object', properties: {} } } },
]
