// cron-styles.ts —— 定时任务样式（从 CronView 拆出，行为不变）
export const S = {
  root: {
    display: 'flex',
    flexDirection: 'column' as const,
    height: '100%',
    backgroundColor: 'var(--bg-root)',
    color: 'var(--text-primary)',
    overflow: 'hidden',
  },
  header: {
    padding: '20px 24px 0',
    flexShrink: 0,
  },
  titleRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginBottom: '4px',
  },
  icon: { fontSize: '28px' },
  title: { fontSize: '20px', fontWeight: 600 as const, color: 'var(--text-primary)', margin: 0 },
  subtitle: { fontSize: '12px', color: 'var(--text-secondary)' },
  // body
  body: {
    flex: 1,
    overflowY: 'auto' as const,
    padding: '16px 24px 24px',
  },
  // create section
  createCard: {
    background: 'var(--bg-card)',
    border: '1px solid var(--border)',
    borderRadius: '12px',
    padding: '16px',
    marginBottom: '16px',
  },
  createTitle: {
    fontSize: '14px',
    fontWeight: 600 as const,
    color: 'var(--warning)',
    marginBottom: '12px',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  createRow: {
    display: 'flex',
    gap: '8px',
    marginBottom: '10px',
    flexWrap: 'wrap' as const,
  },
  input: {
    background: 'var(--bg-elevated)',
    border: '1px solid var(--border)',
    color: 'var(--text-primary)',
    padding: '8px 12px',
    borderRadius: '6px',
    fontSize: '13px',
    outline: 'none',
    flex: 1,
    minWidth: '120px',
  },
  inputSmall: {
    background: 'var(--bg-elevated)',
    border: '1px solid var(--border)',
    color: 'var(--text-primary)',
    padding: '8px 12px',
    borderRadius: '6px',
    fontSize: '13px',
    outline: 'none',
    flex: 2,
    minWidth: '150px',
  },
  select: {
    background: 'var(--bg-elevated)',
    border: '1px solid var(--border)',
    color: 'var(--text-primary)',
    padding: '8px 10px',
    borderRadius: '6px',
    fontSize: '13px',
    outline: 'none',
    cursor: 'pointer',
    minWidth: '130px',
  },
  btnPrimary: {
    padding: '8px 20px',
    borderRadius: '6px',
    border: 'none',
    background: 'var(--accent)',
    color: 'var(--on-accent)',
    fontSize: '13px',
    fontWeight: 600 as const,
    cursor: 'pointer',
    whiteSpace: 'nowrap' as const,
  },
  btnGhost: {
    padding: '6px 12px',
    borderRadius: '6px',
    border: '1px solid var(--border)',
    background: 'transparent',
    color: 'var(--text-secondary)',
    fontSize: '11px',
    cursor: 'pointer',
    whiteSpace: 'nowrap' as const,
  },
  // preset chips
  presetRow: {
    display: 'flex',
    gap: '6px',
    flexWrap: 'wrap' as const,
    marginBottom: '12px',
  },
  presetChip: (active: boolean) => ({
    padding: '4px 10px',
    borderRadius: '14px',
    border: active ? '1px solid var(--accent)' : '1px solid var(--border)',
    background: active ? 'var(--skin-accent-soft)' : 'transparent',
    color: active ? 'var(--text-primary)' : 'var(--text-secondary)',
    fontSize: '11px',
    cursor: 'pointer',
    whiteSpace: 'nowrap' as const,
    transition: 'all .12s',
  }),
  // template section
  templateSection: {
    marginBottom: '12px',
  },
  templateLabel: {
    fontSize: '11px',
    color: 'var(--text-secondary)',
    marginBottom: '6px',
  },
  templateRow: {
    display: 'flex',
    gap: '6px',
    flexWrap: 'wrap' as const,
  },
  templateChip: {
    padding: '5px 12px',
    borderRadius: '14px',
    border: '1px solid var(--border-glow)',
    background: 'rgba(212, 175, 55, 0.08)',
    color: 'var(--warning)',
    fontSize: '11px',
    cursor: 'pointer',
    whiteSpace: 'nowrap' as const,
  },
  // filter tabs
  filterRow: {
    display: 'flex',
    gap: '4px',
    marginBottom: '12px',
    borderBottom: '1px solid var(--border)',
    paddingBottom: '8px',
  },
  filterTab: (active: boolean) => ({
    padding: '5px 14px',
    borderRadius: '6px',
    border: 'none',
    background: active ? 'rgba(var(--skin-accent),.15)' : 'transparent',
    color: active ? 'var(--accent)' : 'var(--text-secondary)',
    cursor: 'pointer',
    fontSize: '12px',
    fontWeight: active ? (600 as const) : (400 as const),
    transition: 'all .12s',
  }),
  // stats
  statsBar: {
    display: 'flex',
    gap: '12px',
    marginBottom: '12px',
    flexWrap: 'wrap' as const,
  },
  statChip: {
    fontSize: '11px',
    color: 'var(--text-secondary)',
    background: 'var(--bg-elevated)',
    border: '1px solid var(--border)',
    borderRadius: '6px',
    padding: '5px 12px',
  },
  statNum: { fontWeight: 700 as const, color: 'var(--accent)', marginRight: '4px' },
  // task card
  card: (enabled: boolean) => ({
    background: 'var(--bg-card)',
    border: enabled ? '2px solid var(--success)' : '1px solid var(--border)',
    borderRadius: '10px',
    padding: '12px 16px',
    marginBottom: '8px',
    opacity: enabled ? 1 : 0.55,
    transition: 'all .15s',
  }),
  cardHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '8px',
  },
  cardName: {
    fontSize: '15px',
    fontWeight: 600 as const,
    color: 'var(--text-primary)',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  statusDot: (enabled: boolean) => ({
    width: '8px',
    height: '8px',
    borderRadius: '50%',
    background: enabled ? 'var(--success)' : '#555',
    flexShrink: 0,
  }),
  cardActions: {
    display: 'flex',
    gap: '6px',
    alignItems: 'center',
  },
  btnIcon: {
    width: '30px',
    height: '30px',
    borderRadius: '6px',
    border: '1px solid var(--border)',
    background: 'transparent',
    color: 'var(--text-secondary)',
    fontSize: '14px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnDanger: {
    width: '30px',
    height: '30px',
    borderRadius: '6px',
    border: '1px solid rgba(220,53,69,0.3)',
    background: 'transparent',
    color: 'var(--danger)',
    fontSize: '14px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  // toggle switch
  toggle: (on: boolean) => ({
    position: 'relative' as const,
    width: '42px',
    height: '24px',
    borderRadius: '12px',
    background: on ? 'var(--success)' : 'var(--border-glow)',
    cursor: 'pointer',
    transition: 'background .15s',
    border: 'none',
    flexShrink: 0,
  }),
  toggleKnob: (on: boolean) => ({
    position: 'absolute' as const,
    top: '2px',
    left: on ? '20px' : '2px',
    width: '20px',
    height: '20px',
    borderRadius: '50%',
    background: 'var(--text-primary)',
    transition: 'left .15s',
  }),
  // meta row
  metaRow: {
    display: 'flex',
    gap: '16px',
    flexWrap: 'wrap' as const,
    marginBottom: '6px',
  },
  metaItem: {
    fontSize: '11px',
    color: 'var(--text-secondary)',
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
  },
  metaLabel: { color: 'var(--text-muted)' },
  metaValue: { color: 'var(--text-primary)' },
  // countdown
  countdownBadge: {
    fontSize: '12px',
    fontWeight: 600 as const,
    color: 'var(--warning)',
    background: 'rgba(212,175,55,0.1)',
    border: '1px solid rgba(212,175,55,0.25)',
    borderRadius: '4px',
    padding: '2px 8px',
  },
  // prompt preview
  promptPreview: {
    fontSize: '12px',
    color: 'var(--text-secondary)',
    lineHeight: 1.5,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
    maxWidth: '100%',
  },
  // empty / loading
  empty: {
    textAlign: 'center' as const,
    padding: '40px 20px',
    color: 'var(--text-muted)',
    fontSize: '13px',
  },
  // confirm
  confirmOverlay: {
    background: 'var(--bg-card)',
    border: '1px solid var(--border)',
    borderRadius: '10px',
    padding: '16px',
    marginBottom: '12px',
    textAlign: 'center' as const,
  },
  confirmText: { fontSize: '13px', color: 'var(--text-primary)', marginBottom: '10px' },
  confirmBtns: { display: 'flex', gap: '8px', justifyContent: 'center' },
  btnConfirm: {
    padding: '6px 18px',
    borderRadius: '6px',
    border: 'none',
    background: 'var(--danger)',
    color: 'var(--on-accent)',
    fontSize: '12px',
    fontWeight: 600 as const,
    cursor: 'pointer',
  },
  btnCancel: {
    padding: '6px 18px',
    borderRadius: '6px',
    border: '1px solid var(--border)',
    background: 'transparent',
    color: 'var(--text-secondary)',
    fontSize: '12px',
    cursor: 'pointer',
  },
}

// ─── component ───────────────────────────────────────

