// knowledge-styles.ts —— 藏书阁样式（从 KnowledgeView 拆出，行为不变）
export const S = {
  root: {
    display: 'flex',
    flexDirection: 'column' as const,
    height: '100%',
    overflow: 'hidden',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '14px 24px',
    borderBottom: '1px solid var(--border)',
    flexShrink: 0,
    gap: '12px',
  } as React.CSSProperties,
  headerTitle: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  headerIcon: {
    fontSize: '24px',
  },
  headerH1: {
    fontSize: '18px',
    fontWeight: 600 as const,
    color: 'var(--accent)',
  },
  headerSub: {
    fontSize: '11px',
    color: 'var(--text-muted)',
  },
  statsRow: {
    display: 'flex',
    gap: '16px',
  },
  statBadge: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    padding: '4px 14px',
    background: 'var(--bg-card)',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius)',
    fontSize: '11px',
    color: 'var(--text-secondary)',
  },
  statVal: {
    fontSize: '16px',
    fontWeight: 700 as const,
    color: 'var(--accent-purple)',
  },
  body: {
    flex: 1,
    overflowY: 'auto' as const,
    padding: '16px 24px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '16px',
  },
  section: {
    background: 'var(--bg-card)',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius-lg)',
    padding: '16px',
  },
  sectionTitle: {
    fontSize: '12px',
    fontWeight: 600 as const,
    color: 'var(--accent)',
    marginBottom: '10px',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  sectionIcon: {
    fontSize: '14px',
  },
  /* import */
  importRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    flexWrap: 'wrap' as const,
  },
  formatHint: {
    fontSize: '11px',
    color: 'var(--text-muted)',
  },
  importMsg: {
    fontSize: '11px',
    marginTop: '6px',
    minHeight: '16px',
  },
  /* search */
  searchRow: {
    display: 'flex',
    gap: '8px',
  },
  searchInput: {
    flex: 1,
    padding: '7px 10px',
    borderRadius: 'var(--radius)',
    border: '1px solid var(--border)',
    background: 'var(--bg-elevated)',
    outline: 'none',
    fontSize: '12px',
    color: 'var(--text-primary)',
    fontFamily: 'inherit',
  },
  searchBtn: {
    padding: '7px 14px',
    background: 'var(--accent)',
    color: 'var(--on-accent)',
    border: 'none',
    borderRadius: 'var(--radius)',
    cursor: 'pointer',
    fontSize: '12px',
    fontWeight: 600 as const,
  },
  results: {
    marginTop: '10px',
    maxHeight: '300px',
    overflowY: 'auto' as const,
  },
  resultItem: {
    background: 'var(--bg-elevated)',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius)',
    padding: '10px 12px',
    marginBottom: '6px',
  },
  resultHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: '4px',
    fontSize: '11px',
  },
  resultScore: {
    color: 'var(--accent-green)',
    fontWeight: 600 as const,
  },
  resultContent: {
    fontSize: '12px',
    color: 'var(--text-secondary)',
    lineHeight: 1.5,
    whiteSpace: 'pre-wrap' as const,
    wordBreak: 'break-word' as const,
    maxHeight: '120px',
    overflowY: 'auto' as const,
  },
  /* doc library */
  docList: {
    maxHeight: '220px',
    overflowY: 'auto' as const,
  },
  docItem: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '8px 10px',
    borderRadius: 'var(--radius)',
    borderBottom: '1px solid var(--border)',
    transition: 'background .12s',
  },
  docInfo: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '2px',
    flex: 1,
    minWidth: 0,
  },
  docName: {
    fontSize: '12px',
    color: 'var(--text-primary)',
    fontWeight: 500 as const,
    whiteSpace: 'nowrap' as const,
    overflow: 'hidden',
    textOverflow: 'ellipsis' as const,
  },
  docMeta: {
    fontSize: '10px',
    color: 'var(--text-muted)',
    display: 'flex',
    gap: '10px',
  },
  docDel: {
    background: 'none',
    border: '1px solid var(--border)',
    color: 'var(--text-muted)',
    padding: '2px 8px',
    borderRadius: 'var(--radius-sm)',
    cursor: 'pointer',
    fontSize: '11px',
    flexShrink: 0,
  },
  emptyHint: {
    fontSize: '12px',
    color: 'var(--text-muted)',
    padding: '20px 0',
    textAlign: 'center' as const,
  },
  /* Q&A */
  qaInputRow: {
    display: 'flex',
    gap: '8px',
  },
  qaInput: {
    flex: 1,
    padding: '7px 10px',
    borderRadius: 'var(--radius)',
    border: '1px solid var(--border)',
    background: 'var(--bg-elevated)',
    outline: 'none',
    fontSize: '12px',
    color: 'var(--text-primary)',
    fontFamily: 'inherit',
  },
  qaBtn: {
    padding: '7px 14px',
    background: 'var(--accent-purple)',
    color: 'var(--on-accent)',
    border: 'none',
    borderRadius: 'var(--radius)',
    cursor: 'pointer',
    fontSize: '12px',
    fontWeight: 600 as const,
  },
  qaContextBox: {
    marginTop: '10px',
    padding: '10px 12px',
    background: 'var(--bg-elevated)',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius)',
    maxHeight: '200px',
    overflowY: 'auto' as const,
    fontSize: '12px',
    color: 'var(--text-secondary)',
    lineHeight: 1.5,
    whiteSpace: 'pre-wrap' as const,
  },
  qaLabel: {
    fontSize: '10px',
    color: 'var(--text-muted)',
    marginBottom: '6px',
    textTransform: 'uppercase' as const,
    letterSpacing: '.5px',
  },
  spinner: {
    display: 'inline-block',
    width: '12px',
    height: '12px',
    border: '2px solid var(--border)',
    borderTopColor: 'var(--accent)',
    borderRadius: '50%',
    animation: 'spin .6s linear infinite',
  } as React.CSSProperties,
}

/* ─── component ─── */


