// skills-styles.ts —— 技能精神录样式（从 SkillsView 拆出，行为不变）
export const S: Record<string, React.CSSProperties> = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    backgroundColor: 'var(--bg-root)',
    color: 'var(--text-primary)',
    overflowY: 'auto',
    padding: '24px 28px',
    position: 'relative',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 14,
    flexShrink: 0,
    gap: 16,
  },
  title: {
    fontSize: 22,
    fontWeight: 600,
    color: 'var(--accent)',
    margin: 0,
    marginBottom: 2,
  },
  subtitle: {
    fontSize: 'var(--ui-font-size)',
    color: 'var(--text-secondary)',
    margin: 0,
  },
  headerActions: {
    display: 'flex',
    gap: 8,
    alignItems: 'center',
    flexShrink: 0,
  },

  /* stats bar */
  statsBar: {
    display: 'flex',
    gap: 16,
    padding: '10px 16px',
    background: 'var(--bg-card)',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius-lg)',
    marginBottom: 20,
    flexShrink: 0,
    flexWrap: 'wrap',
  },
  statItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 5,
    fontSize: 'calc(var(--ui-font-size) - 1px)',
  },
  statLabel: {
    color: 'var(--text-secondary)',
  },
  statCount: {
    fontWeight: 600,
    minWidth: 18,
    textAlign: 'center',
  },

  /* error */
  errorBar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    background: 'var(--danger-soft)',
    border: '1px solid var(--danger-soft)',
    color: '#ff6680',
    padding: '8px 14px',
    borderRadius: 'var(--radius)',
    marginBottom: 14,
    fontSize: 'calc(var(--ui-font-size) - 1px)',
    flexShrink: 0,
  },

  /* empty */
  empty: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '64px 20px',
    flex: 1,
  },
  emptyIcon: {
    fontSize: 56,
    opacity: 0.5,
  },

  /* grid */
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(290px, 1fr))',
    gap: 12,
    alignContent: 'start',
  },

  /* card */
  card: {
    background: 'var(--bg-card)',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius-lg)',
    padding: '16px 18px',
    display: 'flex',
    flexDirection: 'column',
  },
  cardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  cardIcon: {
    fontSize: 20,
  },
  badge: {
    fontSize: 'calc(var(--ui-font-size) - 3px)',
    padding: '2px 10px',
    borderRadius: 10,
    border: '1px solid',
    fontWeight: 500,
    lineHeight: '16px',
  },
  cardTitle: {
    fontSize: 'calc(var(--ui-font-size) + 2px)',
    fontWeight: 600,
    color: 'var(--text-primary)',
    margin: '0 0 6px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  cardDesc: {
    fontSize: 'calc(var(--ui-font-size) - 1px)',
    color: 'var(--text-secondary)',
    margin: '0 0 10px',
    flex: 1,
    lineHeight: 1.5,
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
    overflow: 'hidden',
  },
  cardPath: {
    fontSize: 'calc(var(--ui-font-size) - 3px)',
    color: 'var(--text-muted)',
    fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
    marginBottom: 12,
    wordBreak: 'break-all',
    opacity: 0.7,
  },
  cardActions: {
    display: 'flex',
    gap: 8,
  },

  /* modal */
  overlay: {
    position: 'fixed',
    inset: 0,
    backgroundColor: 'var(--overlay)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 200,
  },
  modal: {
    background: 'var(--bg-elevated)',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius-lg)',
    width: '92%',
    maxWidth: 560,
    maxHeight: '82vh',
    display: 'flex',
    flexDirection: 'column',
    boxShadow: '0 16px 48px rgba(0,0,0,0.55)',
  },
  modalHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    padding: '16px 20px',
    borderBottom: '1px solid var(--border)',
    flexShrink: 0,
  },
  modalTitle: {
    fontSize: 'calc(var(--ui-font-size) + 3px)',
    fontWeight: 600,
    margin: 0,
    color: 'var(--text-primary)',
  },
  modalBody: {
    padding: 20,
    overflowY: 'auto',
    flex: 1,
    minHeight: 0,
  },
  modalFooter: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: 8,
    padding: '12px 20px',
    borderTop: '1px solid var(--border)',
    flexShrink: 0,
  },
  textarea: {
    width: '100%',
    background: 'var(--bg-root)',
    border: '1px solid var(--border)',
    color: 'var(--text-primary)',
    padding: 10,
    borderRadius: 'var(--radius)',
    fontSize: 'calc(var(--ui-font-size) - 1px)',
    fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
    resize: 'vertical',
    outline: 'none',
    minHeight: 140,
    boxSizing: 'border-box',
  },

  /* viewer */
  viewerPath: {
    fontSize: 'calc(var(--ui-font-size) - 2px)',
    color: 'var(--text-muted)',
    fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
    marginBottom: 14,
    padding: '6px 12px',
    background: 'var(--bg-root)',
    borderRadius: 'var(--radius-sm)',
    border: '1px solid var(--border)',
  },
  viewerContent: {
    fontSize: 'var(--ui-font-size)',
    lineHeight: 1.7,
    color: 'var(--text-primary)',
    wordBreak: 'break-word',
    overflowWrap: 'break-word',
  },

  /* toast */
  toast: {
    position: 'fixed',
    bottom: 28,
    left: '50%',
    transform: 'translateX(-50%)',
    background: 'var(--bg-elevated)',
    border: '1px solid var(--accent)',
    color: 'var(--text-primary)',
    padding: '10px 24px',
    borderRadius: 'var(--radius-lg)',
    fontSize: 'var(--ui-font-size)',
    zIndex: 300,
    boxShadow: '0 6px 24px rgba(0,0,0,0.45)',
    whiteSpace: 'nowrap',
  },
}

