// ui-styles.ts —— 高频内联样式常量（收敛重复 style={{...}}，行为不变）
import type { CSSProperties } from 'react'

export const U: Record<string, CSSProperties> = {
  // 布局
  pageBody: { flex: 1, padding: '20px 24px', overflowY: 'auto' },
  flex1: { flex: 1 },
  flex1min0: { flex: 1, minWidth: 0 },
  shrink0: { flexShrink: 0 },
  ellipsis1: { flex: 1, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
  inlineFlex4: { display: 'inline-flex', alignItems: 'center', gap: 4 },
  inlineFlex5: { display: 'inline-flex', alignItems: 'center', gap: 5 },
  flexGap3: { display: 'flex', gap: 3, flexShrink: 0 },
  flexGap8shrink: { display: 'flex', alignItems: 'center', gap: 8, flexShrink: 0 },
  flexEnd: { display: 'flex', gap: 8, justifyContent: 'flex-end' },
  center: { textAlign: 'center' },
  none: { display: 'none' },
  mt8: { marginTop: 8 },
  mt10: { marginTop: 10 },
  // 文本
  textMuted: { color: 'var(--text-muted)' },
  accent: { color: 'var(--accent)' },
  tinyMuted: { fontSize: 'calc(var(--ui-font-size) - 4px)', color: 'var(--text-muted)' },
  fs2b600: { fontSize: 'calc(var(--ui-font-size) - 2px)', fontWeight: 600, color: 'var(--text-primary)' },
  fs2label: { fontSize: 'calc(var(--ui-font-size) - 2px)', color: 'var(--text-secondary)' },
  sectionPurple: { fontSize: 'calc(var(--ui-font-size) - 2px)', fontWeight: 700, color: 'var(--accent-purple)', margin: '10px 0 4px' },
  // 表格单元
  thCell: { padding: '6px 8px', fontWeight: 600, textAlign: 'center' },
  thCell2: { padding: '6px 8px', textAlign: 'center' },
  thCellOk: { padding: '6px 8px', textAlign: 'center', color: 'var(--success)' },
  ellipsis: { overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
  stopBtn: { width: 36, height: 36, minWidth: 36, borderRadius: '50%', fontSize: 18, background: '#cc3333' },
  b600: { fontWeight: 600 },
  wrap8: { flexWrap: 'wrap', gap: 8 },
  px12: { padding: '1px 12px' },
  danger: { color: 'var(--danger)' },
  mt6px: { marginTop: '6px' },
  gap4: { display: 'flex', gap: 4 },
  gap6: { display: 'flex', gap: 6 },
  gap8mt10: { display: 'flex', gap: 8, marginTop: 10 },
  mt4: { marginTop: 4 },
  gap8mt6: { display: 'flex', gap: 8, marginTop: 6 },
  centerGap8: { display: 'flex', alignItems: 'center', gap: 8 },
  mt6: { marginTop: 6 },
  gap6ml4: { display: 'flex', gap: 6, marginLeft: 4 },
  wrap8mt8: { display: 'flex', gap: 8, marginTop: 8, alignItems: 'center', flexWrap: 'wrap' },
  centerGap8mt6: { display: 'flex', alignItems: 'center', gap: 8, marginTop: 6 },
  fs2muted: { fontSize: 'calc(var(--ui-font-size) - 2px)', color: 'var(--text-muted)' },
  rightMt8: { textAlign: 'right', marginTop: 8 },
  rightMb8: { textAlign: 'right', marginBottom: 8 },
  endMt12: { display: 'flex', gap: 8, justifyContent: 'flex-end', marginTop: 12, alignItems: 'center' },
  betweenMb8: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
  centerGap8Mb12: { display: 'flex', alignItems: 'center', gap: 8, marginBottom: 12 },
  scrollMb14: { flex: 1, overflowY: 'auto', marginBottom: 14 },
  betweenMb18: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 18 },
  grid3: { display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 8 },
  centerGap5Mb6: { display: 'flex', justifyContent: 'center', gap: 5, marginBottom: 6 },
  column1: { flex: 1, minWidth: 0, display: 'flex', flexDirection: 'column', gap: 1 },
  betweenGap10Mb7: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 10, marginBottom: 7 },
  between16: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 16 },
}
